# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'playbyplay' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Invites'

  # Pods for playbyplay

  target 'playbyplayTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'playbyplayUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
